
import React, { useState, useEffect, useRef } from 'react';
import { generateDeepMindAnalysis } from '../services/geminiService';
import { Language } from '../types';
import { 
  Sparkles, 
  BrainCircuit, 
  Send, 
  User, 
  Quote, 
  Scroll, 
  BookOpen, 
  Printer, 
  Download, 
  ShieldCheck, 
  Terminal, 
  Cpu, 
  Workflow,
  Search,
  AlertCircle,
  ShieldAlert,
  FileText,
  ChevronRight
} from 'lucide-react';

interface DeepMindReport {
  title: string;
  executiveSummary: string;
  strategicSynthesis: string;
  councilVoices: {
    strategist: string;
    quote: string;
    application: string;
  }[];
  conclusion: string;
}

interface ReportAnalyzerProps {
  language?: Language;
}

export const ReportAnalyzer: React.FC<ReportAnalyzerProps> = ({ language = Language.FRENCH }) => {
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [loadStage, setLoadStage] = useState(0);
  const [report, setReport] = useState<DeepMindReport | null>(null);
  const [error, setError] = useState<string | null>(null);

  const reportContainerRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);

  // Aggressive text cleaning for professional display as requested
  const cleanReportText = (text: string) => {
    if (!text) return "";
    return text
      .replace(/[\*#\[\]]/g, '') // Strip symbols: * # [ ]
      .replace(/_{1,2}/g, '')    // Strip underscores
      .replace(/`{1,3}/g, '')    // Strip backticks
      .trim();
  };

  const t = {
    [Language.ENGLISH]: {
      title: 'Mugi-Solo Strategic Core',
      subtitle: 'Synthesis of Burundi internal security architecture (PNB/SNR/FDN) and real-time OSINT.',
      placeholder: 'Query Strategic Intel...',
      loading: [
        'Initiating Deep Reasoning Protocols...',
        'Consulting Council of Strategists (Machiavelli/Sun Tzu/Clausewitz)...',
        'Cross-referencing 2004 Police Law with 2005 Constitutional frameworks...',
        'Synthesizing SNR and PNB Jurisdictional friction points...',
        'Compiling Multi-Page Strategic Dissertation...'
      ],
      awaiting: 'Awaiting Strategic Query...',
      download: 'Export Intelligence Dossier',
      print: 'Print Briefing',
      summary: 'Executive Summary',
      synthesis: 'Exhaustive Strategic Dissertation',
      verdict: 'Final Strategic Verdict',
      council: 'The Council of Strategists',
      generated: 'Generated by Salus Mugi-Solo // Grade A Intelligence',
      error: 'Intelligence Blackout: Unable to synthesize current request.',
      suggested: 'Priority Deep Dives'
    },
    [Language.FRENCH]: {
      title: 'Noyau Stratégique Mugi-Solo',
      subtitle: 'Synthèse de l\'architecture de sécurité intérieure (PNB/SNR/FDN) et OSINT en temps réel.',
      placeholder: 'Interroger le renseignement...',
      loading: [
        'Initialisation des protocoles de raisonnement profond...',
        'Consultation du Conseil des Stratèges (Machiavelli/Sun Tzu/Clausewitz)...',
        'Référencement croisé de la loi de 2004 avec les cadres constitutionnels de 2005...',
        'Synthèse des points de friction juridictionnels entre le SNR et la PNB...',
        'Compilation de la dissertation stratégique multipage...'
      ],
      awaiting: 'En attente d\'une requête stratégique...',
      download: 'Exporter le Dossier de Renseignement',
      print: 'Imprimer le Briefing',
      summary: 'Résumé Exécutif',
      synthesis: 'Dissertation Stratégique Exhaustive',
      verdict: 'Verdict Stratégique Final',
      council: 'Le Conseil des Stratèges',
      generated: 'Généré par Salus Mugi-Solo // Renseignement Grade A',
      error: 'Blackout du renseignement : Impossible de synthétiser la requête.',
      suggested: 'Analyses Profondes'
    },
    [Language.KIRUNDI]: {
      title: 'Ubumenyi bwa Mugi-Solo',
      subtitle: 'Amakuru y\'umutekano (PNB/SNR/FDN) n\'ivyerekeye igihugu ubu.',
      placeholder: 'Baza amakuru akomeye...',
      loading: [
        'Gutangura uburyo bwa Mugi-Solo bwo gushira hamwe ubumenyi...',
        'Kubaza abahuza (Sun Tzu, Machiavelli, n\'abandi)...',
        'Gusuzuma amategeko yo mu 2004 n\'ibwirizwa nshingiro ryo mu 2005...',
        'Gushira hamwe ubumenyi bwa SNR n\'igipolisi...',
        'Gukora raporo nini cane...'
      ],
      awaiting: 'Rindira ubumenyi...',
      download: 'Gura raporo PDF',
      print: 'Sohora raporo',
      summary: 'Incabwenge y\'amakuru',
      synthesis: 'Inkuru Nini cane y\'Ubumenyi',
      verdict: 'Icemezo ca nyuma',
      council: 'Amajwi y\'abahuza',
      generated: 'Vyozwe na Mugi-Solo',
      error: 'Hari amakuru atabonetse. Ongera ugerageze.',
      suggested: 'Ibibazo byihariye'
    }
  }[language];

  const suggestedQueries = {
    [Language.ENGLISH]: [
      "Deep dive: Gitega Province population, challenges, and MP controversies.",
      "Link Analysis: [Person Name] influence in East Africa (Politics, Security, Economy).",
      "Forensic MP OSINT: Marital status, criminal charges, and sentiment in Ngozi.",
      "EAC Security Link: Burundi-DRC border friction and SNR operational depth."
    ],
    [Language.FRENCH]: [
      "Analyse profonde: Province de Gitega, défis et controverses des députés.",
      "Analyse de liens: Influence de [Nom] en Afrique de l'Est (Politique, Sécurité, Économie).",
      "OSINT Député: État civil, charges criminelles et sentiment à Ngozi.",
      "Lien de sécurité EAC: Friction frontalière Burundi-RDC et profondeur du SNR."
    ],
    [Language.KIRUNDI]: [
      "Ubushakashatsi bwimbitse: Intara ya Gitega, ibibazo n'abashingamateka.",
      "Isesengura ry'imikoranire: [Izina] muri Afurika y'uburasirazuba.",
      "Amakuru y'abashingamateka: Umuryango, ivyaha, n'ivyo abantu babavugako.",
      "Umutekano mu karere: Imipaka y'u Burundi na RDC."
    ]
  }[language];

  useEffect(() => {
    let interval: any;
    if (loading) {
      interval = setInterval(() => {
        setLoadStage(prev => (prev + 1) % t.loading.length);
      }, 5000);
    } else {
      setLoadStage(0);
    }
    return () => clearInterval(interval);
  }, [loading, t.loading.length]);

  const handleAnalyze = async (forcedQuery?: string) => {
    const q = forcedQuery || query;
    if (!q.trim()) return;
    setLoading(true);
    setReport(null);
    setError(null);
    try {
      const result = await generateDeepMindAnalysis(q, language);
      if (result) {
        setReport(result);
      } else {
        setError(t.error);
      }
    } catch (err) {
      console.error(err);
      setError(t.error);
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPDF = async () => {
    if (!contentRef.current || !window.html2canvas || !window.jspdf) {
      alert("Intelligence Export Libraries not loaded. Please wait.");
      return;
    }
    try {
      const canvas = await window.html2canvas(contentRef.current, { scale: 1.5, useCORS: true, backgroundColor: '#ffffff' });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new window.jspdf.jsPDF('p', 'mm', 'a4');
      const imgProps = pdf.getImageProperties(imgData);
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
      
      let heightLeft = pdfHeight;
      let position = 0;

      pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight);
      heightLeft -= 297;

      while (heightLeft >= 0) {
        position = heightLeft - pdfHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight);
        heightLeft -= 297;
      }

      pdf.save(`Salus_DeepMind_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (error) {
      alert("Export failed.");
    }
  };

  return (
    <div className="h-full flex flex-col gap-6 animate-fade-in pb-20">
      {/* Header Panel */}
      <div className="bg-slate-900 border border-slate-700 rounded-xl p-8 shadow-2xl relative overflow-hidden group">
        <div className="absolute top-0 right-0 p-8 opacity-5 group-hover:opacity-10 transition-opacity">
          <ShieldAlert size={120} />
        </div>
        <div className="flex items-center gap-6 relative z-10">
          <div className="p-5 bg-blue-600/20 rounded-2xl text-blue-400 border border-blue-500/30 shadow-[0_0_20px_rgba(37,99,235,0.2)]">
            <BrainCircuit size={48} className="animate-pulse" />
          </div>
          <div>
            <h2 className="text-4xl font-black text-white mb-2 tracking-tight uppercase italic">{t.title}</h2>
            <p className="text-slate-400 text-lg max-w-2xl font-medium leading-relaxed">{t.subtitle}</p>
          </div>
        </div>
      </div>

      {/* Input Module */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 print:hidden">
        <div className="lg:col-span-3 space-y-4">
          <div className="bg-slate-800 p-6 rounded-xl border border-slate-700 shadow-xl relative">
            <div className="relative">
              <Terminal className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500" size={20} />
              <input 
                type="text" 
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleAnalyze()}
                placeholder={t.placeholder}
                className="w-full bg-slate-950 border border-slate-600 rounded-xl py-4 pl-14 pr-16 text-lg text-white placeholder-slate-600 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 transition-all font-mono"
                disabled={loading}
              />
              <button 
                onClick={() => handleAnalyze()}
                disabled={!query.trim() || loading}
                className="absolute right-3 top-1/2 -translate-y-1/2 bg-blue-600 hover:bg-blue-500 text-white p-3 rounded-lg transition-all disabled:opacity-50 shadow-lg"
              >
                {loading ? <Workflow className="animate-spin" size={20} /> : <Send size={20} />}
              </button>
            </div>
          </div>
          
          <div className="flex flex-wrap gap-2">
            <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest py-2 mr-2">Quick Dives:</span>
            {suggestedQueries.map((sq, i) => (
              <button 
                key={i} 
                onClick={() => { setQuery(sq); handleAnalyze(sq); }}
                className="text-xs bg-slate-800/50 hover:bg-slate-700 border border-slate-700 text-slate-400 hover:text-white px-4 py-2 rounded-full transition-all flex items-center gap-2"
              >
                <Search size={12} /> {sq}
              </button>
            ))}
          </div>
        </div>

        <div className="bg-slate-900 border border-slate-800 p-6 rounded-xl flex flex-col justify-center gap-4">
          <div className="flex items-center gap-3">
             <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></div>
             <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">Quantum SSR Sync</span>
          </div>
          <div className="space-y-2">
            <div className="flex justify-between text-[10px] font-mono text-slate-500">
               <span>LATENCY</span>
               <span className="text-green-500">OPTIMAL</span>
            </div>
            <div className="flex justify-between text-[10px] font-mono text-slate-500">
               <span>DEPTH</span>
               <span className="text-blue-500">EXHAUSTIVE</span>
            </div>
          </div>
        </div>
      </div>

      {/* Results Module */}
      <div ref={reportContainerRef} className="print:w-full min-h-[400px]">
        {loading ? (
          <div className="flex flex-col items-center justify-center py-32 text-center space-y-8 bg-slate-900/50 rounded-xl border border-dashed border-slate-700">
            <div className="relative">
              <div className="w-24 h-24 border-4 border-slate-800 border-t-blue-500 rounded-full animate-spin"></div>
              <Cpu className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-blue-400 animate-pulse" size={32} />
            </div>
            <div className="max-w-md">
              <h3 className="text-2xl font-bold text-white mb-2">Processing Strategic Synthesis...</h3>
              <p className="text-blue-400 font-mono text-xs uppercase tracking-[0.3em] mb-4 h-4 transition-all">
                {t.loading[loadStage]}
              </p>
              <div className="w-full bg-slate-800 h-1.5 rounded-full overflow-hidden">
                <div 
                  className="bg-blue-500 h-full transition-all duration-1000 ease-linear" 
                  style={{ width: `${((loadStage + 1) / t.loading.length) * 100}%` }}
                ></div>
              </div>
            </div>
          </div>
        ) : error ? (
          <div className="p-12 text-center bg-red-900/10 border border-red-500/20 rounded-xl flex flex-col items-center gap-4">
            <AlertCircle className="text-red-500" size={48} />
            <p className="text-red-400 font-medium">{error}</p>
            <button onClick={() => handleAnalyze()} className="text-white bg-red-600 px-6 py-2 rounded-lg text-sm font-bold">Retry</button>
          </div>
        ) : report ? (
          <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="flex justify-end gap-3 mb-6 print:hidden">
              <button onClick={handleDownloadPDF} className="flex items-center gap-2 px-6 py-3 bg-slate-800 hover:bg-slate-700 text-white rounded-xl transition-all text-sm font-bold border border-slate-700">
                <Download size={18} /> {t.download}
              </button>
              <button onClick={() => window.print()} className="flex items-center gap-2 px-6 py-3 bg-slate-800 hover:bg-slate-700 text-white rounded-xl transition-all text-sm font-bold border border-slate-700">
                <Printer size={18} /> {t.print}
              </button>
            </div>

            <div ref={contentRef} className="bg-[#fdfbf7] text-slate-900 rounded-xl shadow-2xl overflow-hidden border border-slate-200">
              {/* Header */}
              <div className="bg-[#0f172a] text-white p-12 md:p-16 border-b-8 border-blue-600 relative">
                <div className="absolute top-0 right-0 p-12 opacity-10">
                   <ShieldCheck size={140} />
                </div>
                <div className="relative z-10 max-w-4xl">
                  <div className="flex items-center gap-3 mb-8">
                    <span className="bg-blue-600 text-[10px] font-black uppercase tracking-[0.4em] px-4 py-1.5 rounded-full">SSR Dissertation</span>
                    <span className="text-slate-500 text-[10px] font-mono tracking-widest uppercase">MUGI-SOLO // CONFIDENTIAL</span>
                  </div>
                  <h1 className="text-5xl md:text-7xl font-black font-playfair leading-[1.1] mb-12 uppercase italic tracking-tighter">
                    {report.title}
                  </h1>
                  <div className="bg-white/5 backdrop-blur-xl p-10 rounded-3xl border border-white/10 shadow-inner">
                    <h3 className="text-xs font-black text-blue-400 uppercase tracking-[0.3em] mb-6 flex items-center gap-3">
                       <FileText size={16} /> {t.summary}
                    </h3>
                    <p className="text-white text-2xl leading-relaxed font-merriweather font-light">
                      {cleanReportText(report.executiveSummary)}
                    </p>
                  </div>
                </div>
              </div>

              {/* Body */}
              <div className="p-12 md:p-20 bg-[#fdfbf7] grid grid-cols-1 lg:grid-cols-12 gap-20">
                <div className="lg:col-span-8 space-y-20">
                  <section>
                    <h3 className="flex items-center gap-3 text-3xl font-black text-[#0f172a] mb-12 border-b-4 border-slate-100 pb-6 uppercase tracking-tighter font-playfair italic">
                      <BookOpen className="text-blue-600" size={32} /> {t.synthesis}
                    </h3>
                    <div className="text-slate-900 leading-[2.4] font-merriweather text-xl tracking-normal">
                      <div className="whitespace-pre-line space-y-16">
                        {cleanReportText(report.strategicSynthesis)}
                      </div>
                    </div>
                  </section>

                  <section className="bg-slate-950 text-white p-14 rounded-3xl shadow-2xl relative overflow-hidden border border-slate-800">
                    <div className="absolute top-0 right-0 p-6 opacity-10">
                      <Sparkles size={80} />
                    </div>
                    <h3 className="flex items-center gap-3 text-sm font-black text-blue-400 mb-10 uppercase tracking-[0.4em]">
                      <Terminal size={22} /> {t.verdict}
                    </h3>
                    <p className="text-4xl font-bold italic leading-relaxed font-playfair tracking-tight">
                      "{cleanReportText(report.conclusion)}"
                    </p>
                  </section>
                </div>

                {/* Sidebar */}
                <aside className="lg:col-span-4 space-y-12">
                  <div className="sticky top-32">
                    <h3 className="text-xs font-black text-slate-400 uppercase tracking-[0.4em] mb-8 border-l-4 border-blue-600 pl-6">{t.council}</h3>
                    <div className="space-y-10">
                      {report.councilVoices?.map((voice, idx) => (
                        <div key={idx} className="bg-white p-10 rounded-3xl shadow-lg border border-slate-100 hover:border-blue-500 transition-all group relative">
                          <div className="flex items-center gap-4 mb-8">
                            <div className="w-14 h-14 bg-slate-50 rounded-2xl flex items-center justify-center text-slate-400 group-hover:bg-blue-600 group-hover:text-white transition-all shadow-sm">
                              <User size={28} />
                            </div>
                            <span className="text-lg font-black text-slate-900 uppercase tracking-tighter">{voice.strategist}</span>
                          </div>
                          <div className="relative mb-8">
                            <Quote className="text-blue-50 absolute -top-8 -left-8" size={64} />
                            <p className="text-slate-800 italic font-merriweather text-xl leading-relaxed relative z-10 pl-2">"{cleanReportText(voice.quote)}"</p>
                          </div>
                          <div className="bg-slate-50 p-8 rounded-2xl text-xs text-slate-600 border border-slate-100 leading-loose">
                            <span className="font-black text-blue-700 uppercase block mb-3 tracking-widest">Strategy Application</span>
                            {cleanReportText(voice.application)}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </aside>
              </div>

              {/* Footer */}
              <div className="bg-slate-50 p-12 text-center border-t border-slate-200 flex flex-col md:flex-row justify-between items-center px-20 gap-8">
                <div className="flex items-center gap-6">
                  <div className="p-4 bg-blue-600 text-white rounded-2xl shadow-xl">
                    <ShieldCheck size={32} />
                  </div>
                  <div className="text-left">
                    <span className="text-xs text-slate-500 font-black uppercase tracking-[0.5em] block mb-1">{t.generated}</span>
                    <span className="text-[10px] text-slate-400 font-mono">ENCRYPTED OUTPUT // NODE-BDI-X</span>
                  </div>
                </div>
                <div className="text-right">
                   <p className="text-[10px] text-slate-400 font-mono uppercase tracking-widest">Protocol: Arusha Forensic Standard</p>
                   <p className="text-[10px] text-slate-400 font-mono mt-1">{new Date().toUTCString()}</p>
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div className="h-[600px] flex flex-col items-center justify-center text-slate-600 border-8 border-dashed border-slate-800 rounded-[3rem] bg-slate-900/10 group">
            <div className="p-10 bg-slate-800/50 rounded-full mb-8 group-hover:scale-110 transition-all duration-700 shadow-2xl">
              <Scroll size={80} className="opacity-10 text-blue-400" />
            </div>
            <p className="text-3xl font-black text-slate-700 uppercase tracking-[0.3em]">{t.awaiting}</p>
            <p className="text-xs text-slate-800 mt-4 font-mono tracking-widest">ID-SYNC-PENDING // STANDBY</p>
          </div>
        )}
      </div>
    </div>
  );
};
